from snakemake.utils import min_version, validate

min_version("6.0")  # Temporarily lowered for testing

configfile: "config/config.yaml"


validate(config, schema="../schemas/config.schema.yaml")

include: "rules/common.smk"
include: "rules/download.smk"
include: "rules/standardize.smk"
include: "rules/qc.smk"
include: "rules/orthology.smk"
include: "rules/annotation.smk"
include: "rules/validation.smk"
include: "rules/liftoff.smk"
include: "rules/matrices.smk"
include: "rules/expression.smk"
include: "rules/reporting.smk"
include: "rules/ingest.smk"


rule all:
    input:
        "results/reports/summary.html",
